### ISSUE TITLE
Irradiated drones and ablative drones don't mix

### ISSUE THREAD

**Issue by Ant-Throw-Pology** [landgreen/n-gon#119]
When I have irradiated drones and ablative drones, and I take damage, the drones created aren't irradiated.

**Comment by 3xionDev** [comment]
It's because the game does not consider drones generated via ablative drones to actually be drones created by the player. It easy to see this because ablative drones does _not_ unlock irradiated drones in the experiment menu. That being said, I don't think that should be the case. Maybe throw out a suggestion to landgreen.

**Comment by landgreen** [comment]
The thing is if you are getting hit a bunch in a small space and you keep spawning Irradiated drones it would be super annoying.
