### ISSUE TITLE
Make accretion a skin tech

### ISSUE THREAD

**Issue by Masbirb** [landgreen/n-gon#158]
I consider accretion just a straight upgrade to quenching as it doesn't cheat hp and it gives hp power ups upon taking and I consider this a good enough nerf

**Comment by kgurchiek** [comment]
I fully agree with this, since accretion's release I haven't taken quenching a single time so that it wouldn't ruin accretion if I happened to get it. There's no reason to take damage to gain max health when you can just take that extra health with you, which effectively acts as your actual health anyway.

**Comment by landgreen** [comment]
quenching is good with recycling, CPT symmetry, ablative drones, and any build with high defense

**Comment by kgurchiek** [comment]
Even if you have perfect 100% defense, that still only makes it just as good as accretion, not really better. I can see why recycling would be better with quenching, but why CPT symmetry and ablative drones? As far as I can tell they aren't affected by max health

**Comment by Masbirb** [comment]
However quenching the is very bad with Zeno's paradox because you take more damage every 5 seconds

**Comment by Masbirb** [comment]
This nerf would also not affect the synergy between cpt symmetry and quenching
