### ISSUE TITLE
Bug?: Being able to use laser while time is frozen

### ISSUE THREAD

**Issue by The-Rock-21** [landgreen/n-gon#191]
This may or may not be a bug but I'm pretty sure stopping time should also stop the laser from doing anything.
![Screenshot 2024-03-20 7 32 01 AM](https://github.com/landgreen/n-gon/assets/101891804/61e62856-b599-42d1-b1fc-91fbdb8dbc71)

**Comment by AnnonymousNerd87** [comment]
This isn't a bug its been around for years

**Comment by The-Rock-21** [comment]
oh ok

**Comment by AnnonymousNerd87** [comment]
also a lore reason laser works while dilating is because time dilation isn't a time freeze, it's a dilation. because the speed of light is so fast even if you slowed it down more than 99.99% it would still look instantaneous. also even if it didn't travel near instantaneously because all light would be slowed, including visible light, you would think its instantaneous.
