### ISSUE TITLE
Suggestion: Randomized Field theory

### ISSUE THREAD

**Issue by corneeme** [landgreen/n-gon#220]
For each level switch your field to a random field and convert field tech, spawn ten coupling at the end of the level (the little blue orbs I'm pretty sure that's what they're called)

**Comment by AnnonymousNerd87** [comment]
so like a mix of integrated armament, WIMPS, and generalist?

**Comment by AnnonymousNerd87** [comment]
might want to give some other bonus as well because coupling on its own isn't that strong for some fields like grappling hook and perfect diamagnetism

**Comment by corneeme** [comment]
i was also thinking like +20% damage or defense

**Comment by corneeme** [comment]
we could also increase the coupling amount

**Comment by AnnonymousNerd87** [comment]
I was thinking along those lines, but I feel like you could just get
interest and any other coupling tech to outcompete it and get more
benefits. also many worlds is a better version of this because many worlds
gives a free tech each level, which is more valuable than most coupling
bonuses (also grappling hook needs a drastic buff to coupling because bonus
ammo isn't that valuable and in some cases completely useless)

**Comment by corneeme** [comment]
yeah, I just had the idea and thought that the randomization of fields and field techs would be good, I just knew it wasn't enough for it to be a good mechanic

**Comment by AnnonymousNerd87** [comment]
maybe a junk

**Comment by corneeme** [comment]
oh yeah, that would make so much more sense
