### ISSUE TITLE
I think I found an exploit or something by accident

### ISSUE THREAD

**Issue by bobsburgers72** [landgreen/n-gon#233]
![Screenshot 2024-05-01 9 44 40 AM](https://github.com/landgreen/n-gon/assets/153040489/50da359b-97e4-40c8-acae-c4acae1cbb80)
I accidentally found a way to get lots of damage with accretion disk, interest, duplication, and some other tech
it also causes the game to lag quite a bit

**Comment by bobsburgers72** [comment]
I didn't even mean for this to happen
I was just playing the game normally and I found this

**Comment by 3xionDev** [comment]
this is not much information to go off of. could you provide more details about exactly how you did this?

**Comment by bobsburgers72** [comment]
all I remember was getting 2 interest tech, accretion disk, an ammo tech, replication, cross-disciplinary, futures exchange, and some other techs that increase damage

**Comment by AnihilationPA** [comment]
Oh i know why, due to supply chain, normally it doubles every gun's ammo independently, but in this new update supply chain gives the same amount of ammo you already have atm IN ALL YOUR GUNS in ammo powerups to you. if you only have one gun, it should double the # of bullets you had in your only gun, No problem. But lets say you have nail gun with 600 ammo, harpoon with 20 ammo, and missiles with 60 ammo. Getting supply chain will now spawn 600+20+60 ammo in total, amounting to 680 ammo, 80 more than expected for nail gun, 640 more for harpoon and 560 more for missiles (these were calculated by (All gun ammo x 2) - (current ammo of one gun x 2))
So yeah this new supply chain is somewhat op

**Comment by myschoolisass** [comment]
intentional
plus nerf interest
