### ISSUE TITLE
Porn in tech images

### ISSUE THREAD

**Issue by Yaron-Ha** [landgreen/n-gon#250]
Played n-gon today, got a porn image for "reinforced learning"
Might want to check out the image source you use for JUNK

**Comment by kgurchiek** [comment]
That's very weird, according to the openverse docs mature content is disabled by default. Even when mature content is manually enabled I don't get any mature results for "reinforced learning": https://api.openverse.engineering/v1/images/?q=reinforced%20learning&mature=true

**Comment by kgurchiek** [comment]
Actually it is in there, it's named "reinforcement learning (51589363322)" and isn't marked as mature. I'm not sure if there's any way to detect that, but maybe change it to only use the first few image results so that they're more relevant, but since the search is purely based on name there's no guarantee that it isn't an nsfw image like this one.

**Comment by 3xionDev** [comment]
this made me nearly spit my water out when I saw the title lmao

**Comment by landgreen** [comment]
ok, well I'll remove the JUNK images for now.
