### ISSUE TITLE
Minor issue; molecular assembler is boring

### ISSUE THREAD

**Issue by AnnonymousNerd87** [landgreen/n-gon#262]
not much to say, it just doesn't have the extra juice of a good field. It's just passive damage, and molecular assembler + inductive charging makes the game even more boring. You just sit around corners, not firing your gun, just letting drones/spores/ice9/missiles kill everything while you fall asleep. I feel like it should reward m for being active, maybe it only produces stuff after you kill a mob or deal a certain amount of damage. maybe it could consume nearby blocks when you hold your field, releasing field explodes out in drones/spores/ice9/missiles based on the mass of blocks consumed, forcing you to be aggressive and kill mobs to harvest their mass to add to your assembler. I just don't want it to stay as the energy regen go brrrrrrrr field.

**Comment by kgurchiek** [comment]
That's a really good point, I never really thought about it that way but molecular assembler really does just reward you for being active. I get incentivizing the player to be careful and take it slow, which some of the bosses do, but making it beneficial to just sit and do nothing isn't very good for gameplay (in my opinion, at least). Maybe instead of just producing things for each kill it could have a short timer, so for each kill you get 3 seconds where you're able to produce things, and then it stops. I imagine it being displayed visually on the player like the damage boost powerups.

**Comment by landgreen** [comment]
...
molecular assembler is my favorite field

**Comment by kgurchiek** [comment]
Molecular assembler is definitely one of my favorites too, it's a cool concept and is fun to mess around with, but it falls into the problem a lot of games fall into where the best strategies aren't the fun ones, so you end up having to sacrifice some fun to do better at the game or vice versa. Pilot wave is the opposite, it's my favorite field because of how fun it is, but it just isn't that good in practice so it isn't a viable option if you're trying to do as good as possible.

**Comment by landgreen** [comment]
Fields are designed to be more of a personal choice, so it's cool to like some and not like some. 

I play molecular assembler in an active way on the why mode I've been working on.  I'm mostly trying to figure out a way to not die with the reduced mobility and defense of the field.  It's fun!

(also I'm old and I like that molecular assembler doesn't hurt my wrists as much to use)

**Comment by kgurchiek** [comment]
I think it should at least have some cap though, high energy or coupling builds are made op with molecular assembler because you can basically just afk and kill everything. Most "god runs" I see people do either use an insane amount of bots or molecular assembler to basically become unstoppable, at which point the game becomes boring because there's no linger any challenge, it's an easy win even on why mode. Don't get me wrong, molecular assembler is great and fun if you play it for the fun, but I just think in its current state it rewards playstyles that aren't fun more than ones that are. While it is your choice to play that way, most gamers are prioritizing doing as good as possible, regardless of fun. It's why you can look up so many grindy xp farms in pretty much any game that has an xp system. Most games try to make the fun playstyles rewarding, so that those people still end up having a lot of fun and enjoying the game. I personally think The Finals does this really well, wacky strategies with crazy movement and whatnot are both really effective and really fun.

**Comment by landgreen** [comment]
If you can win every time or even 1/5 of the time with a low skill build on why mode I'd be surprised.  I think people stuck doing a boring, but effective build need to try a harder difficulty.

That's kinda the point of the next patch.
I want to make setting a higher difficulty a more obvious choice so people will fun the right level of fun.
Lots of folks don't even know there are difficulty modes.

**Comment by kgurchiek** [comment]
Yeah, a lot of people I talk to don't even know there are settings because they ignore the start menu entirely, that's another reason having the difficulty menu be an in-game powerup is a great idea.

**Comment by AnnonymousNerd87** [comment]
This was some great commentary, I'm closing now.

**Comment by Masbirb** [comment]
In the word of every game design book players will optimize the fun out of your game. I believe that the problem with molecular assembler is that it works just as well if not better when playing passively compared to playing actively. We can make molecular assembler more active by adding techs that increase energy or energy efficiency when surrounded by mobs so for max dps you need to be surrounded while you still can sit back and let your drones or spores do the work for you slowly.

**Comment by AnnonymousNerd87** [comment]
that's why I feel that consuming blocks for mass to assemble would be cool,
the primary method of obtaining blocks is killing mobs, without being
stranded if you run out.

**Comment by AnnonymousNerd87** [comment]
you could reuse the wormhole code for absorbing blocks, when you hold field
a one-way hole opens in front of you, when you release it will construct
(drones, spores, ice9, missiles, etc.) based on block mass

**Comment by landgreen** [comment]
sorry everyone.  I'm just completely on a different page here.  I think molecular assembler is the best field with the most fun gameplay.  I think the passive way ya'll are thinking about is really only an issue on lower difficulty.

**Comment by AnnonymousNerd87** [comment]
actually the main problem comes from inductive charging

**Comment by AnnonymousNerd87** [comment]
inductive charging, reduced tolerances, coupling, your choice of drone tech
= sit around a corner holding crouch

**Comment by AnnonymousNerd87** [comment]
without inductive charging it's a great field

**Comment by AnnonymousNerd87** [comment]
and because of players optimizing the fun out of anything, they will always
take inductive charging

**Comment by landgreen** [comment]
Well we will just have to agree to disagree, but I love getting inductive charging.  It makes it more fun.  On harder difficulty levels crouching in one place without a defensive field isn't easy.
