### ISSUE TITLE
Wiki links not working as intended

### ISSUE THREAD

**Issue by Whyisthisnotavalable** [landgreen/n-gon#69]
Try clicking on the link for the colony tech. It doesn't lead you to the right page.

**Comment by Whyisthisnotavalable** [comment]
You can also try mycelial fragmentation, or any other tech with the the link: `` in them.

**Comment by landgreen** [comment]
I disabled custom links a while back mostly because wikipedia article names keep changing and it's not worth constantly updating.  It just searches wikipedia every time now.  If the search is a good match it goes directly to a page and if there isn't a good match you get some options.

so not a bug.
